AllCops:
  Exclude:
    - 'config/**/*'
    - '**/bin/**/*'
    - 'app/mailers/**/*'
    - 'test/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
  