AllCops:
  Exclude:
    - 'config/**/*'
    - '**/bin/**/*'
    - 'app/mailers/**/*'
    - 'test/**/*'
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/BlockLength:
  Max: 100
  