default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>z
  host: localhost
  username: <%= ENV["POSTGRES_USER"] || "postgres" %>
  password: <%= ENV["POSTGRES_PASSWORD"] || "postgres" %>
  
development:
  <<: *default
  database: uex_contact_list_development

test:
  <<: *default
  database: uex_contact_list_test

production:
  <<: *default
  database: uex_contact_list_production
  username: uex_contact_list
  password: <%= ENV["UEX_CONTACT_LIST_DATABASE_PASSWORD"] %>
